### ISSUE TITLE
The Basics Tutorial

### ISSUE THREAD

**Issue by krixano** [krixano/ZeroNet-Dev-Center#1]
This will be the tutorial that introduces the very basics needed in order to start creating zites. It will cover how zites work, where they are stored, how they are updated, how content.json files are constructed, and how a zite is kept secure using signatures. You can view the tutorial [here](https://github.com/krixano/ZeroNet-Dev-Center/blob/master/tutorials/TheBasics.md).

Topics Covered:
1. [x] Introduction ( @krixano )
2. [x] Creating A Zite ( @krixano, @AnthyG )
3. [x] The Sidebar ( @AnthyG )
    - [x] Zite Address
    - [x] Changing Basic Zite Settings
4. [x] Where You Zite is Stored Locally
5. [x] Content.json File - What is It? ( @krixano )
6. [x] Signing the Content.json File ( @krixano )
7. [x] How Zites Are Kept Secure ( @krixano )
8. [x] Publishing Your Zite
9. [x] Keeping Your Zite Online
10. [x] Updating Your Zite

*Topics and their orders may change in the future.*

**Comment by AnthyG** [comment]
Added section "The Sidebar" with commit https://github.com/AnthyG/ZeroNet-Dev-Center/commit/64a4d0df4425609c1e58c60281fe99331f098e7a

**Comment by krixano** [comment]
I think the `How Does ZeroNet Know Who Owns A Zite` section should talk about these things:
* Your private key for the zite being stored in the users.json file
* How your signature is used within the content.json file.

Because of the second one, I might want to put this section after the content.json section. A better name for this section might also be "How Does ZeroNet Keep Your Zite Secure", where we can also talk about how a signature is formed and how a visitor to the zite verifies that the owner is the one who signed the content.json file (maybe link to another site/tutorial that talks about keys and Digital Signatures more in depth?), etc.

**Comment by AnthyG** [comment]
Doesn't ZeroNet know, that you own the zite, because you signed the `content.json`-File with your own (?private or public?) key?
This would mean, that the complete `How Does ZeroNet Know Who Owns A Zite`-Section would come _after_ `Signing the Content.json File`, don't you think?

🤔

**Comment by krixano** [comment]
Yep, that's what I was thinking also. Not sure why I had it before the content.json section to begin with. Also, I'm wondering if the `How Does ZeroNet Keep Your Zite Secure` section can be merged with the `Signing the Content.json FIle` section.

**Comment by krixano** [comment]
For the updating your zite section, I wan't to talk about how peers get the updates to the zite and how they determine that it is a newer version.

**Comment by krixano** [comment]
It may also be good to create footnotes that link to more in depth tutorials about certain topics that are just briefly talked about here. For example, the ZeroFrame API, Cryptography and Digital Signatures, etc.
