### ISSUE TITLE
Dynamic Markdown-loading System

### ISSUE THREAD

**Issue by AnthyG** [krixano/ZeroNet-Dev-Center#2]
This "Dynamic System" should load a Tutorials Markdown-File and present it in HTML, which means, the file can't be accessed directly (e.g. `/tutorials/Tutorial_1.html`), but has to be accessed via query-string (e.g. `/tutorials?Tutorial_1`).
Then of course, there also has to be a dynamic list on the main `/tutorials`-Page, containing all the tutorials in the subdir `/tutorials`.
The list probably has to be saved in the Database (which is, kind of already happening (but there is an error with the `json`-Table)).

The system at it's base, won't be that hard to code (just FYI 😉) (Markdown-it should work just fine, I think).

**Comment by krixano** [comment]
I already got the markdown thing done being parsed and outputed. You have to go to the `tutorials/tutorial.html` page. I just recently put a link to that on the homepage. Also, what is the error with the json Table?

**Comment by AnthyG** [comment]
Just synced the commit of yours with that, but it's not exactly what I meant, because you still need to add a `.html`-File for every markdown-file. The way, I'm thinking of it, would be to just have _one_ `.html`-File which would parse every markdown-file, e.g.:
`/tutorials/index.html`, and then via the querystring `?p=Tutorial_1` or `?Tutorial_1`. This could also be accessed via `/tutorials/` or `/tutorials` (I'm not sure if the latter one works though).

The problem that currently exists with the `json`-Table, is that there is that you added it to `tables` in `dbschema.json`-File, but not to `maps`.

**Comment by krixano** [comment]
Yes, that's what I'm gonna do - I just haven't done it yet. I'm looking up how to do querystrings. I wasn't sure if you seen the file where I am actually parsing and outputting the markdown or not.

**Comment by krixano** [comment]
I don't have the `json` table in the `maps` section for Important Zites either.

**Comment by AnthyG** [comment]
1. [Regarding the query-string](https://stackoverflow.com/a/901144/5712160)
2. Oh LOL 😲⁉️

**Comment by krixano** [comment]
It's because I forgot to change the `version` and `schema_changed` numbers when I modified the dbschema.json file.

**Comment by krixano** [comment]
Almost done with this. I'm trying to now use `history.pushState()`, but is isn't working. Do you know if there is another solution for this.

**Comment by krixano** [comment]
Nvm, there's a function for it in the ZeroFrame API.

**Comment by AnthyG** [comment]
So... I just created the dynamic list function, but because of Git, I couldn't merge your commits into my branch, and now I have to manually copy over all your files 💀

**Comment by krixano** [comment]
You should be able to resolve any conflicts.

**Comment by AnthyG** [comment]
Nope, I discarded them, without knowing, that I can't update from your branch again, if doing so 😐

**Comment by AnthyG** [comment]
And BTW, the Database is still not working for me.. 🤔

**Comment by krixano** [comment]
I'm not sure why it wouldn't... except that I didn't include the `data/tutorials.json` file in the github repo.

**Comment by krixano** [comment]
I noticed before you used `fileQuery`. Is that better than using `dbQuery`?

**Comment by AnthyG** [comment]
Hmm, it depends.
If you don't want to join data from multiple files (for example, a profile picture or so, which would be saved in the users own `data.json`-File), then I don't think, much speaks _against_ using `fileQuery`..
But if you want to join data from multiple files, then `dbQuery` is clearly the better option.

**Comment by krixano** [comment]
I think you can force pull a branch by doing something like this `git pull --force`

**Comment by AnthyG** [comment]
I think, I'm now in sync with your branch 
![image](https://user-images.githubusercontent.com/15957203/28493916-11003294-6f20-11e7-891d-fb4d94a46eab.png)

**Comment by krixano** [comment]
I noticed that using ZeroFrame's pushState is slightly different from using history.pushState. I want to do something like `history.pushState(null, '', '/tutorials/?t=' + tutorial.slug)` which makes the address go to `.../tutorials/?t=the_basics` (according to a StackOverflow answer). However, when using a similar thing with the ZeroFrame API, the address shows up as `/?/t=the_basics` which messes up if someone copies that to try to go to that page. Do you know a fix for this?

**Comment by krixano** [comment]
Hold on... if that says up to date, does that mean you lost the `The Sidebar` section that you wrote?

**Comment by AnthyG** [comment]
Nah, kept that, and it didn't say anything either..
But you don't have that yet, do you!?

**Comment by AnthyG** [comment]
Maybe I should do a pull-request, to tidy stuff up, because I'm 9 commits ahead, though I only changed the  "Basics" tutorial..

**Comment by krixano** [comment]
No, so why is it saying that your branch doesn't have any changes?

**Comment by AnthyG** [comment]
That is, indeed, weird 😆

**Comment by krixano** [comment]
I just went to create a new pull request with your branch and now it is showing the changes.

**Comment by AnthyG** [comment]
And the changes are probably just all the reformations because of my editor 😐

**Comment by krixano** [comment]
Yeah, I use tabs for all of my stuff instead of spaces. It seems like a lot of people uses spaces instead of tabs.

**Comment by AnthyG** [comment]
yeah 😅

**Comment by krixano** [comment]
The problem was I was putting `'/?t='` instead of just `'?t='`.

**Comment by krixano** [comment]
Oh, I know why the pull request you were showing was saying there were no changes, it's because it was showing it for creating a pull request from my branch to yours rather than from yours to mine.

**Comment by AnthyG** [comment]
Oh, didn't notice that 😲

Just as a question, does the wrapperPustState work from the main directory for you (it still makes the same error as mentioned before, for me)?

**Comment by krixano** [comment]
I used this `page.cmd('wrapperPushState', [null, '', '']);` with an empty string for the last argument.

**Comment by AnthyG** [comment]
I meant for example, this: `page.cmd("wrapperPushState", [{}, "", "/tutorials"])`

**Comment by krixano** [comment]
Are you trying to remove the `?t=` part from the url? If so, using an empty string in place of `"/tutorials"` seemed to work for me.

**Comment by krixano** [comment]
Or are you meaning going to `"/tutorials"` from the root index page?

**Comment by AnthyG** [comment]
Yes, to the second one.

**Comment by krixano** [comment]
I believe the question mark is required, I'm not sure.

**Comment by AnthyG** [comment]
No, I don't think so, the docs about the javascript-function (not ZeroNet API), don't say anything anything about this..

**Comment by krixano** [comment]
Next, I need to reload the tutorial's text that is being shown (and the tutorial list) whenever there is a change with the database and the markdown file.

**Comment by AnthyG** [comment]
Do you want to do that live?
I mean,... hmm
😆

It has to be, doesn't it? Because if the user just keeps navigating through the different tutorials, everything just gets loaded from the Vue-App, right!?

**Comment by krixano** [comment]
Yeah. I need to know when a file changes so I can reload the text from the file. Isn't there a way to see if the database changes using the `onRequest()` function?

**Comment by AnthyG** [comment]
You could just put a `setInterval(function () { reloadTutos(); }, afterXms)` somewhere..
And, as far as I know, it only fires, if the user has the tab open.

**Comment by krixano** [comment]
I am having one more problem, when you go from the tutorials list into a tutorial, then hit the back button, it doesn't go back to the tutorial list.

**Comment by AnthyG** [comment]
That's because the browser decides, if it wants to load the page.
I think this is what you're searching for: [window.onpopstate](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate)
