### ISSUE TITLE
Databases In ZeroNet

### ISSUE THREAD

**Issue by krixano** [krixano/ZeroNet-Dev-Center#29]
This will give the most basic concepts on how databases work within ZeroNet. I was going to put this into the Database Basics tutorial; however, what this new one will contain is essential information for understanding the Users In ZeroNet tutorial.

This tutorial should talk about content.json files, what they are used for. A very short description of the dbschema file. How json files are used to store information. How the database is reloaded upon a change of the dbschema file. How the database is rebuilt (modified?) when a modified json file has been received.

**Comment by anoadragon453** [comment]
Looks like this has been at least partially completed in the Users and Databases tutorial.

**Comment by krixano** [comment]
@anoadragon453 Yeah, this was merged into the Users and Databases tutorial. I was originally gonna make them seperate, which is why this issue is here, but decided not to.
