### ISSUE TITLE
Footnote-Links not working correct

### ISSUE THREAD

**Issue by AnthyG** [krixano/ZeroNet-Dev-Center#5]
They link back to `/tutorials#FOOTNOTE`, not `/tutorial/?t=TUTORIAL#FOOTNOTE`.

**Comment by krixano** [comment]
This only happens when you click on the tutorial from the tutorial list. If you go directly to the tutorial using its proper url, the links work correctly. So, this has something to do with the `pushState` stuff. I'm not quite sure how to fix this.
