### ISSUE TITLE
Create a ZeroNet plugin tutorial

### ISSUE THREAD

**Issue by rllola** [krixano/ZeroNet-Dev-Center#8]
Hello,

Would a tutorial on how to create a plugin have its place on ZeroNet Dev Center ? It is not directly linked to zite but allow to enhance ZeroNet and can also introduce new feature in zite.

**Comment by krixano** [comment]
Now that I'm thinking about it, I don't see why not! However, I don't know anything about ZeroNet's Client and how plugins work, etc. So other people will have to create the tutorials. If you feel like you can/want to create a tutorial, feel free. Right now, you have to fork this repo, create a markdown file of it in the `tutorials` directory and create a pull request. I'll hopefully eventually get to creating a system that will let people make tutorials directly on the zite.

**Comment by rllola** [comment]
I started to write a little something.
This is PR #9 and it is still work in progress. I will try to finish it for next week end.

**Comment by krixano** [comment]
Take as much time as you need. Also, thanks for taking the time in writing a tutorial on this topic!

**Comment by krixano** [comment]
@rllola I have made revisions and edits to your tutorial. I hope that you are okay with these changes: 
https://github.com/krixano/ZeroNet-Dev-Center/commit/ab2070e9ed1a6bd14325ec9a343aabe86e46520e

**Comment by rllola** [comment]
Look good to me. Thanks for your work !

**Comment by krixano** [comment]
No, Thanks for *your* work!
